const categories = [
    "Global Prehistory",
    "Ancient Mediterranean",
    "Early Europe and Colonial Americas",
    "Later Europe and Americas",
    "Indigenous Americas",
    "Africa",
    "West and Central Asia",
    "South, East, and Southeast Asia",
    "The Pacific",
    "Global Contemporary"
];

const artworks = [
    // 1. Global Prehistory (1-11)
    { id: "1", title: "Apollo 11 stones", cat: "Global Prehistory", img: "" },
    { id: "2", title: "Great Hall of the Bulls", cat: "Global Prehistory", img: "" },
    { id: "3", title: "Camelid sacrum", cat: "Global Prehistory", img: "" },
    { id: "4", title: "Running horned woman", cat: "Global Prehistory", img: "" },
    { id: "5", title: "Beaker with ibex motifs", cat: "Global Prehistory", img: "" },
    { id: "6", title: "Anthropomorphic stele", cat: "Global Prehistory", img: "" },
    { id: "7", title: "Jade cong", cat: "Global Prehistory", img: "" },
    { id: "8", title: "Stonehenge", cat: "Global Prehistory", img: "" },
    { id: "9", title: "The Ambum Stone", cat: "Global Prehistory", img: "" },
    { id: "10", title: "Tlatilco female figurine", cat: "Global Prehistory", img: "" },
    { id: "11", title: "Terra cotta fragment", cat: "Global Prehistory", img: "" },

    // 2. Ancient Mediterranean (12-47)
    { id: "12", title: "White Temple and its ziggurat", cat: "Ancient Mediterranean", img: "" },
    { id: "13", title: "Palette of King Narmer", cat: "Ancient Mediterranean", img: "" },
    { id: "14", title: "Statues of votive figures", cat: "Ancient Mediterranean", img: "" },
    { id: "15", title: "Seated scribe", cat: "Ancient Mediterranean", img: "" },
    { id: "16", title: "Standard of Ur", cat: "Ancient Mediterranean", img: "" },
    { id: "17", title: "Great Pyramids and Great Sphinx", cat: "Ancient Mediterranean", img: "" },
    { id: "18", title: "King Menkaura and queen", cat: "Ancient Mediterranean", img: "" },
    { id: "19", title: "The Code of Hammurabi", cat: "Ancient Mediterranean", img: "" },
    { id: "20", title: "Temple of Amun-Re and Hypostyle Hall", cat: "Ancient Mediterranean", img: "" },
    { id: "21", title: "Mortuary temple of Hatshepsut", cat: "Ancient Mediterranean", img: "" },
    { id: "22", title: "Akhenaten, Nefertiti, and three daughters", cat: "Ancient Mediterranean", img: "" },
    { id: "23", title: "Tutankhamun's tomb, innermost coffin", cat: "Ancient Mediterranean", img: "" },
    { id: "24", title: "Last judgment of Hu-Nefer", cat: "Ancient Mediterranean", img: "" },
    { id: "25", title: "Lamassu from the citadel of Sargon II", cat: "Ancient Mediterranean", img: "" },
    { id: "26", title: "Athenian agora", cat: "Ancient Mediterranean", img: "" },
    { id: "27", title: "Anavysos Kouros", cat: "Ancient Mediterranean", img: "" },
    { id: "28", title: "Peplos Kore", cat: "Ancient Mediterranean", img: "" },
    { id: "29", title: "Sarcophagus of the Spouses", cat: "Ancient Mediterranean", img: "" },
    { id: "30", title: "Audience Hall of Darius and Xerxes", cat: "Ancient Mediterranean", img: "" },
    { id: "31", title: "Temple of Minerva and Apollo Sculpture", cat: "Ancient Mediterranean", img: "" },
    { id: "32", title: "Tomb of the Triclinium", cat: "Ancient Mediterranean", img: "" },
    { id: "33", title: "Niobides Krater", cat: "Ancient Mediterranean", img: "" },
    { id: "34", title: "Doryphoros (Spear Bearer)", cat: "Ancient Mediterranean", img: "" },
    { id: "35", title: "Acropolis (Parthenon)", cat: "Ancient Mediterranean", img: "" },
    { id: "36", title: "Grave stele of Hegeso", cat: "Ancient Mediterranean", img: "" },
    { id: "37", title: "Winged Victory of Samothrace", cat: "Ancient Mediterranean", img: "" },
    { id: "38", title: "Great Altar of Zeus and Athena at Pergamon", cat: "Ancient Mediterranean", img: "" },
    { id: "39", title: "House of the Vettii", cat: "Ancient Mediterranean", img: "" },
    { id: "40", title: "Alexander Mosaic", cat: "Ancient Mediterranean", img: "" },
    { id: "41", title: "Seated Boxer", cat: "Ancient Mediterranean", img: "" },
    { id: "42", title: "Head of a Roman patrician", cat: "Ancient Mediterranean", img: "" },
    { id: "43", title: "Augustus of Prima Porta", cat: "Ancient Mediterranean", img: "" },
    { id: "44", title: "Colosseum (Flavian Amphitheatre)", cat: "Ancient Mediterranean", img: "" },
    { id: "45", title: "Forum of Trajan", cat: "Ancient Mediterranean", img: "" },
    { id: "46", title: "Pantheon", cat: "Ancient Mediterranean", img: "" },
    { id: "47", title: "Ludovisi Battle Sarcophagus", cat: "Ancient Mediterranean", img: "" },

    // 3. Early Europe and Colonial Americas (48-84)
    { id: "48", title: "Catacomb of Priscilla", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "49", title: "Santa Sabina", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "50", title: "Rebecca and Eliezer at the Well", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "51", title: "San Vitale", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "52", title: "Hagia Sophia", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "53", title: "Merovingian looped fibulae", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "54", title: "Virgin (Theotokos) and Child between Saints", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "55", title: "Lindisfarne Gospels", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "56", title: "Great Mosque of Córdoba", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "57", title: "Pyxis of al-Mughira", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "58", title: "Church of Sainte-Foy", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "59", title: "Bayeux Tapestry", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "60", title: "Chartres Cathedral", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "61", title: "Bibles moralisées", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "62", title: "Röttgen Pietà", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "63", title: "Arena (Scrovegni) Chapel", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "64", title: "Golden Haggadah", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "65", title: "Alhambra", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "66", title: "Annunciation Triptych", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "67", title: "Pazzi Chapel", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "68", title: "The Arnolfini Portrait", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "69", title: "David (Donatello)", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "70", title: "Palazzo Rucellai", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "71", title: "Madonna and Child with Two Angels", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "72", title: "Birth of Venus", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "73", title: "Last Supper", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "74", title: "Adam and Eve", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "75", title: "Sistine Chapel ceiling and altar wall frescoes", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "76", title: "School of Athens", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "77", title: "Isenheim altarpiece", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "78", title: "Entombment of Christ", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "79", title: "Allegory of Law and Grace", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "80", title: "Venus of Urbino", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "81", title: "Frontispiece of the Codex Mendoza", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "82", title: "Il Gesù", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "83", title: "Hunters in the Snow", cat: "Early Europe and Colonial Americas", img: "" },
    { id: "84", title: "Mosque of Selim II", cat: "Early Europe and Colonial Americas", img: "" },

    // 4. Later Europe and Americas (85-152)
    { id: "85", title: "Calling of Saint Matthew", cat: "Later Europe and Americas", img: "" },
    { id: "86", title: "Henri IV Receives the Portrait of Marie de’ Medici", cat: "Later Europe and Americas", img: "" },
    { id: "87", title: "Self-Portrait with Saskia", cat: "Later Europe and Americas", img: "" },
    { id: "88", title: "San Carlo alle Quattro Fontane", cat: "Later Europe and Americas", img: "" },
    { id: "89", title: "Ecstasy of Saint Teresa", cat: "Later Europe and Americas", img: "" },
    { id: "90", title: "Angel with Arquebus", cat: "Later Europe and Americas", img: "" },
    { id: "91", title: "Las Meninas", cat: "Later Europe and Americas", img: "" },
    { id: "92", title: "Woman Holding a Balance", cat: "Later Europe and Americas", img: "" },
    { id: "93", title: "The Palace at Versailles", cat: "Later Europe and Americas", img: "" },
    { id: "94", title: "Screen with the Siege of Belgrade", cat: "Later Europe and Americas", img: "" },
    { id: "95", title: "The Virgin of Guadalupe", cat: "Later Europe and Americas", img: "" },
    { id: "96", title: "Fruit and Insects", cat: "Later Europe and Americas", img: "" },
    { id: "97", title: "Spaniard and Indian Produce a Mestizo", cat: "Later Europe and Americas", img: "" },
    { id: "98", title: "The Tête à Tête", cat: "Later Europe and Americas", img: "" },
    { id: "99", title: "Portrait of Sor Juana Inés de la Cruz", cat: "Later Europe and Americas", img: "" },
    { id: "100", title: "Philosopher Giving a Lecture on the Orrery", cat: "Later Europe and Americas", img: "" },
    { id: "101", title: "The Swing", cat: "Later Europe and Americas", img: "" },
    { id: "102", title: "Monticello", cat: "Later Europe and Americas", img: "" },
    { id: "103", title: "The Oath of the Horatii", cat: "Later Europe and Americas", img: "" },
    { id: "104", title: "George Washington", cat: "Later Europe and Americas", img: "" },
    { id: "105", title: "Self-Portrait", cat: "Later Europe and Americas", img: "" },
    { id: "106", title: "Y no hai remedio", cat: "Later Europe and Americas", img: "" },
    { id: "107", title: "La Grande Odalisque", cat: "Later Europe and Americas", img: "" },
    { id: "108", title: "Liberty Leading the People", cat: "Later Europe and Americas", img: "" },
    { id: "109", title: "The Oxbow", cat: "Later Europe and Americas", img: "" },
    { id: "110", title: "Still Life in Studio", cat: "Later Europe and Americas", img: "" },
    { id: "111", title: "Slave Ship", cat: "Later Europe and Americas", img: "" },
    { id: "112", title: "Palace of Westminster", cat: "Later Europe and Americas", img: "" },
    { id: "113", title: "The Stone Breakers", cat: "Later Europe and Americas", img: "" },
    { id: "114", title: "Nadars Raising Photography", cat: "Later Europe and Americas", img: "" },
    { id: "115", title: "Olympia", cat: "Later Europe and Americas", img: "" },
    { id: "116", title: "The Saint-Lazare Station", cat: "Later Europe and Americas", img: "" },
    { id: "117", title: "The Horse in Motion", cat: "Later Europe and Americas", img: "" },
    { id: "118", title: "The Valley of Mexico", cat: "Later Europe and Americas", img: "" },
    { id: "119", title: "The Burghers of Calais", cat: "Later Europe and Americas", img: "" },
    { id: "120", title: "The Starry Night", cat: "Later Europe and Americas", img: "" },
    { id: "121", title: "The Coiffure", cat: "Later Europe and Americas", img: "" },
    { id: "122", title: "The Scream", cat: "Later Europe and Americas", img: "" },
    { id: "123", title: "Where Do We Come From?", cat: "Later Europe and Americas", img: "" },
    { id: "124", title: "Carson, Pirie, Scott Building", cat: "Later Europe and Americas", img: "" },
    { id: "125", title: "Mont Sainte-Victoire", cat: "Later Europe and Americas", img: "" },
    { id: "126", title: "Les Demoiselles d’Avignon", cat: "Later Europe and Americas", img: "" },
    { id: "127", title: "The Steerage", cat: "Later Europe and Americas", img: "" },
    { id: "128", title: "The Kiss (Gustav Klimt)", cat: "Later Europe and Americas", img: "" },
    { id: "129", title: "The Kiss (Constantin Brancusi)", cat: "Later Europe and Americas", img: "" },
    { id: "130", title: "The Portuguese", cat: "Later Europe and Americas", img: "" },
    { id: "131", title: "Goldfish", cat: "Later Europe and Americas", img: "" },
    { id: "132", title: "Improvisation 28", cat: "Later Europe and Americas", img: "" },
    { id: "133", title: "Self-Portrait as a Soldier", cat: "Later Europe and Americas", img: "" },
    { id: "134", title: "Memorial Sheet for Karl Liebknecht", cat: "Later Europe and Americas", img: "" },
    { id: "135", title: "Villa Savoye", cat: "Later Europe and Americas", img: "" },
    { id: "136", title: "Composition with Red, Blue and Yellow", cat: "Later Europe and Americas", img: "" },
    { id: "137", title: "Results of the First Five-Year Plan", cat: "Later Europe and Americas", img: "" },
    { id: "138", title: "Object (Le Déjeuner en fourrure)", cat: "Later Europe and Americas", img: "" },
    { id: "139", title: "Fallingwater", cat: "Later Europe and Americas", img: "" },
    { id: "140", title: "The Two Fridas", cat: "Later Europe and Americas", img: "" },
    { id: "141", title: "The Migration of the Negro", cat: "Later Europe and Americas", img: "" },
    { id: "142", title: "The Jungle", cat: "Later Europe and Americas", img: "" },
    { id: "143", title: "Dream of a Sunday Afternoon", cat: "Later Europe and Americas", img: "" },
    { id: "144", title: "Fountain (second version)", cat: "Later Europe and Americas", img: "" },
    { id: "145", title: "Woman, I", cat: "Later Europe and Americas", img: "" },
    { id: "146", title: "Seagram Building", cat: "Later Europe and Americas", img: "" },
    { id: "147", title: "Marilyn Diptych", cat: "Later Europe and Americas", img: "" },
    { id: "148", title: "Narcissus Garden", cat: "Later Europe and Americas", img: "" },
    { id: "149", title: "The Bay", cat: "Later Europe and Americas", img: "" },
    { id: "150", title: "Lipstick on Caterpillar Tracks", cat: "Later Europe and Americas", img: "" },
    { id: "151", title: "Spiral Jetty", cat: "Later Europe and Americas", img: "" },
    { id: "152", title: "House in New Castle County", cat: "Later Europe and Americas", img: "" },

    // 5. Indigenous Americas (153-166)
    { id: "153", title: "Chavín de Huántar", cat: "Indigenous Americas", img: "" },
    { id: "154", title: "Mesa Verde cliff dwellings", cat: "Indigenous Americas", img: "" },
    { id: "155", title: "Yaxchilán", cat: "Indigenous Americas", img: "" },
    { id: "156", title: "Great Serpent Mound", cat: "Indigenous Americas", img: "" },
    { id: "157", title: "Templo Mayor", cat: "Indigenous Americas", img: "" },
    { id: "158", title: "Ruler’s feather headdress", cat: "Indigenous Americas", img: "" },
    { id: "159", title: "City of Cusco", cat: "Indigenous Americas", img: "" },
    { id: "160", title: "Maize cobs", cat: "Indigenous Americas", img: "" },
    { id: "161", title: "City of Machu Picchu", cat: "Indigenous Americas", img: "" },
    { id: "162", title: "All-T’oqapu tunic", cat: "Indigenous Americas", img: "" },
    { id: "163", title: "Bandolier bag", cat: "Indigenous Americas", img: "" },
    { id: "164", title: "Transformation mask", cat: "Indigenous Americas", img: "" },
    { id: "165", title: "Painted elk hide", cat: "Indigenous Americas", img: "" },
    { id: "166", title: "Black-on-black ceramic vessel", cat: "Indigenous Americas", img: "" },

    // 6. Africa (167-180)
    { id: "167", title: "Conical tower and circular wall of Great Zimbabwe", cat: "Africa", img: "" },
    { id: "168", title: "Great Mosque of Djenné", cat: "Africa", img: "" },
    { id: "169", title: "Wall plaque, from Oba’s palace", cat: "Africa", img: "" },
    { id: "170", title: "Sika dwa kofi (Golden Stool)", cat: "Africa", img: "" },
    { id: "171", title: "Ndop (portrait figure)", cat: "Africa", img: "" },
    { id: "172", title: "Power figure (Nkisi n’kondi)", cat: "Africa", img: "" },
    { id: "173", title: "Female (Pwo) mask", cat: "Africa", img: "" },
    { id: "174", title: "Portrait mask (Mblo)", cat: "Africa", img: "" },
    { id: "175", title: "Bundu mask", cat: "Africa", img: "" },
    { id: "176", title: "Ikenga (shrine figure)", cat: "Africa", img: "" },
    { id: "177", title: "Lukasa (memory board)", cat: "Africa", img: "" },
    { id: "178", title: "Aka elephant mask", cat: "Africa", img: "" },
    { id: "179", title: "Reliquary figure (nlo bieri)", cat: "Africa", img: "" },
    { id: "180", title: "Veranda post", cat: "Africa", img: "" },

    // 7. West and Central Asia (181-191)
    { id: "181", title: "Petra, Jordan: Treasury and Great Temple", cat: "West and Central Asia", img: "" },
    { id: "182", title: "Buddha (Bamiyan)", cat: "West and Central Asia", img: "" },
    { id: "183", title: "The Kaaba", cat: "West and Central Asia", img: "" },
    { id: "184", title: "Jowo Rinpoche", cat: "West and Central Asia", img: "" },
    { id: "185", title: "Dome of the Rock", cat: "West and Central Asia", img: "" },
    { id: "186", title: "Great Mosque (Isfahan)", cat: "West and Central Asia", img: "" },
    { id: "187", title: "Folio from a Qur’an", cat: "West and Central Asia", img: "" },
    { id: "188", title: "Baptistère de Saint Louis", cat: "West and Central Asia", img: "" },
    { id: "189", title: "Bahram Gur Fights the Karg", cat: "West and Central Asia", img: "" },
    { id: "190", title: "The Court of Gayumars", cat: "West and Central Asia", img: "" },
    { id: "191", title: "The Ardabil Carpet", cat: "West and Central Asia", img: "" },

    // 8. South, East, and Southeast Asia (192-212)
    { id: "192", title: "Great Stupa at Sanchi", cat: "South, East, and Southeast Asia", img: "" },
    { id: "193", title: "Terracotta warriors", cat: "South, East, and Southeast Asia", img: "" },
    { id: "194", title: "Funeral banner of Lady Dai", cat: "South, East, and Southeast Asia", img: "" },
    { id: "195", title: "Longmen caves", cat: "South, East, and Southeast Asia", img: "" },
    { id: "196", title: "Gold and jade crown", cat: "South, East, and Southeast Asia", img: "" },
    { id: "197", title: "Todai-ji", cat: "South, East, and Southeast Asia", img: "" },
    { id: "198", title: "Borobudur Temple", cat: "South, East, and Southeast Asia", img: "" },
    { id: "199", title: "Angkor Wat", cat: "South, East, and Southeast Asia", img: "" },
    { id: "200", title: "Lakshmana Temple", cat: "South, East, and Southeast Asia", img: "" },
    { id: "201", title: "Travelers among Mountains and Streams", cat: "South, East, and Southeast Asia", img: "" },
    { id: "202", title: "Shiva as Lord of Dance", cat: "South, East, and Southeast Asia", img: "" },
    { id: "203", title: "Night Attack on the Sanjô Palace", cat: "South, East, and Southeast Asia", img: "" },
    { id: "204", title: "The David Vases", cat: "South, East, and Southeast Asia", img: "" },
    { id: "205", title: "Portrait of Sin Sukju", cat: "South, East, and Southeast Asia", img: "" },
    { id: "206", title: "Forbidden City", cat: "South, East, and Southeast Asia", img: "" },
    { id: "207", title: "Ryoan-ji", cat: "South, East, and Southeast Asia", img: "" },
    { id: "208", title: "Jahangir Preferring a Sufi Shaikh", cat: "South, East, and Southeast Asia", img: "" },
    { id: "209", title: "Taj Mahal", cat: "South, East, and Southeast Asia", img: "" },
    { id: "210", title: "White and Red Plum Blossoms", cat: "South, East, and Southeast Asia", img: "" },
    { id: "211", title: "Under the Wave off Kanagawa (The Great Wave)", cat: "South, East, and Southeast Asia", img: "" },
    { id: "212", title: "Chairman Mao en Route to Anyuan", cat: "South, East, and Southeast Asia", img: "" },

    // 9. The Pacific (213-223)
    { id: "213", title: "Nan Madol", cat: "The Pacific", img: "" },
    { id: "214", title: "Moai on platform (ahu)", cat: "The Pacific", img: "" },
    { id: "215", title: "‘Ahu ‘ula", cat: "The Pacific", img: "" },
    { id: "216", title: "Staff god", cat: "The Pacific", img: "" },
    { id: "217", title: "Female deity", cat: "The Pacific", img: "" },
    { id: "218", title: "Buk (mask)", cat: "The Pacific", img: "" },
    { id: "219", title: "Hiapo (tapa)", cat: "The Pacific", img: "" },
    { id: "220", title: "Tamati Waka Nene", cat: "The Pacific", img: "" },
    { id: "221", title: "Navigation chart", cat: "The Pacific", img: "" },
    { id: "222", title: "Malagan display and mask", cat: "The Pacific", img: "" },
    { id: "223", title: "Presentation of Fijian mats", cat: "The Pacific", img: "" },

    // 10. Global Contemporary (224-250)
    { id: "224", title: "The Gates", cat: "Global Contemporary", img: "" },
    { id: "225", title: "Vietnam Veterans Memorial", cat: "Global Contemporary", img: "" },
    { id: "226", title: "Horn Players", cat: "Global Contemporary", img: "" },
    { id: "227", title: "Summer Trees", cat: "Global Contemporary", img: "" },
    { id: "228", title: "Androgyne III", cat: "Global Contemporary", img: "" },
    { id: "229", title: "A Book from the Sky", cat: "Global Contemporary", img: "" },
    { id: "230", title: "Pink Panther", cat: "Global Contemporary", img: "" },
    { id: "231", title: "Untitled (#228)", cat: "Global Contemporary", img: "" },
    { id: "232", title: "Dancing at the Louvre", cat: "Global Contemporary", img: "" },
    { id: "233", title: "Trade (Gifts for Trading Land)", cat: "Global Contemporary", img: "" },
    { id: "234", title: "Earth’s Creation", cat: "Global Contemporary", img: "" },
    { id: "235", title: "Rebellious Silence", cat: "Global Contemporary", img: "" },
    { id: "236", title: "En la Barberia no se Llora", cat: "Global Contemporary", img: "" },
    { id: "237", title: "Pisupo Lua Afe", cat: "Global Contemporary", img: "" },
    { id: "238", title: "Electronic Superhighway", cat: "Global Contemporary", img: "" },
    { id: "239", title: "The Crossing", cat: "Global Contemporary", img: "" },
    { id: "240", title: "Guggenheim Museum Bilbao", cat: "Global Contemporary", img: "" },
    { id: "241", title: "Pure Land", cat: "Global Contemporary", img: "" },
    { id: "242", title: "Lying with the Wolf", cat: "Global Contemporary", img: "" },
    { id: "243", title: "Darkytown Rebellion", cat: "Global Contemporary", img: "" },
    { id: "244", title: "The Swing (after Fragonard)", cat: "Global Contemporary", img: "" },
    { id: "245", title: "Old Man’s Cloth", cat: "Global Contemporary", img: "" },
    { id: "246", title: "Stadia II", cat: "Global Contemporary", img: "" },
    { id: "247", title: "Preying Mantra", cat: "Global Contemporary", img: "" },
    { id: "248", title: "Shibboleth", cat: "Global Contemporary", img: "" },
    { id: "249", title: "MAXXI National Museum", cat: "Global Contemporary", img: "" },
    { id: "250", title: "Kui Hua Zi (Sunflower Seeds)", cat: "Global Contemporary", img: "" }
];
